### ISSUE TITLE
Wrong depdendencies are included in secretlint-rule-filter-comments

### ISSUE THREAD

**Issue by azu** [secretlint/secretlint#223]
https://github.com/secretlint/secretlint/blob/4a82dab233c18981376630977ed91d8e0c3c0ba9/packages/%40secretlint/secretlint-rule-filter-comments/package.json#L52-L53

## TODO

- [ ] Remove "lint-staged" (It is not meaningful)
- [ ] Move "prettier" to DevDeps

**Comment by RishiKumarRay** [comment]
do you want to remove this or want to add anything else also?

**Comment by azu** [comment]
I organized tasks.

- [ ] Remove "lint-staged" (It is not meaningful)
- [ ] Move "prettier" to DevDeps
