### ISSUE TITLE
1.0.0 roadmap

### ISSUE THREAD

**Issue by azu** [secretlint/secretlint#25]
## TODO

- [x] README
  - Getting Started
  - Commit Hooks
- [x] Consider Ignoring by default https://github.com/secretlint/secretlint/issues/22
- [x] Config validation https://github.com/secretlint/secretlint/issues/23
- [x] Docker #7

**Comment by azu** [comment]
Docker is after of release

**Comment by azu** [comment]
0.1.0 is released for preview.

**Comment by azu** [comment]
-[ ] need Actual story

**Comment by azu** [comment]
- [ ] easy to integrate

**Comment by azu** [comment]
- [ ] execution type: binary node

**Comment by azu** [comment]
released
