### ISSUE TITLE
Rules: Convert to ESM

### ISSUE THREAD

**Issue by azu** [secretlint/secretlint#530]
- #527 
- #529 

core packages has been migrated to ESM!

rule packages also should be migrated to ESM.

## TODO

- [ ] secretlint-rule-preset-recommend
- [ ] secretlint-rule-preset-canary
- [ ] secretlint-rule-pattern
- [ ] secretlint-rule-slack
- [ ] secretlint-rule-sendgrid
- [ ] secretlint-rule-internal-test-pure-deps
- [ ] secretlint-rule-gcp
- [ ] secretlint-rule-no-homedir
- [ ] secretlint-rule-github
- [ ] secretlint-rule-no-k8s-kind-secret
- [ ] secretlint-rule-secp256k1-privatekey
- [ ] secretlint-rule-example
- [ ] secretlint-rule-no-dotenv
- [ ] secretlint-rule-basicauth
- [ ] secretlint-rule-shopify
- [ ] secretlint-rule-filter-comments
- [ ] secretlint-rule-npm
- [ ] secretlint-rule-azure
- [ ] secretlint-rule-privatekey
- [ ] secretlint-rule-aws
