### ISSUE TITLE
Update globby and replace secretlintignore logics

### ISSUE THREAD

**Issue by azu** [secretlint/secretlint#592]
> Remove ignore option for isGitIgnored and isGitIgnoredSync (https://github.com/sindresorhus/globby/pull/225) https://github.com/sindresorhus/globby/commit/2e43cc47dffd7ea5f5c0ac67b32f719eedb72e4e
>        This option never worked correctly.
> [Release v13.0.0 · sindresorhus/globby](https://github.com/sindresorhus/globby/releases/tag/v13.0.0#)

current implementation uses `ignore` option. We need to update globby and use `ignoreFiles`.

## TODO

- [ ] Add missing test case
- [ ] Update globby
- [ ] Move `DEFAULT_IGNORE_PATTERNS` to `options.ignore` from `ignore`
  - https://github.com/sindresorhus/globby#options
- [ ] Use `ignoreFiles` option as needed

_Originally posted by @azu in https://github.com/secretlint/secretlint/issues/589#issuecomment-1666410345_

**Comment by azu** [comment]
closed by #1530
