### ISSUE TITLE
One Click {introduce/integrate/deploy}

### ISSUE THREAD

**Issue by azu** [secretlint/secretlint#67]
Discuss about One Click *** idea.

**Comment by azu** [comment]
One Click Installation

## Node.js

```
npm install secretlint @secretlint/secretlint-rule-preset-recommend --save-dev && npx secretlint --init
```

and

Husky + Lint-Staged

## Docker

- [ ] How to integrate commit hook

## GitHub Action

Just Create `.github/workflows/secretelint.yml`

## Circle CI

- [ ] use Docker Image

## Travis CI

- [ ] Use Node.js?

**Comment by azu** [comment]
Integrate to GitHub Repository without CLI.

- Install GitHub Actions?

**Comment by azu** [comment]
Add https://github.com/secretlint/secretlint#quick-start section

**Comment by azu** [comment]
resolved
